# Generated by Django 3.1.7 on 2021-06-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210612_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='anailable',
            new_name='available',
        ),
    ]
